export const types = {

    uiOpenModal: '[ui] Open Modal',
    uiCloseModal: '[ui] Close Modal',

    authCheckingFinish: '[auth] Finish checking login state',
    authStartLogin: '[auth] Start login',
    authLogin: '[auth] Login',
    authStartRegister: '[auth] Start Register',
    authStartTokenRenew: '[auth] Start Token Renew',
    authLogout: '[auth] Logout',

    clienteSetActive: '[cliente] Set active',
    clienteLogout: '[cliente] Logout event',
    clienteStartAddNew: '[cliente] Start Add New',
    clienteAddNew: '[cliente] Add new',
    clienteClearActive: '[cliente] Clear active',
    clienteUpdated: '[cliente] Updated',
    clienteDeleted: '[cliente] Deleted',
    clienteLoaded: '[cliente] Loaded',

    elementoSetActive: '[elemento] Set active',
    elementoLogout: '[elemento] Logout event',
    elementoStartAddNew: '[elemento] Start Add New',
    elementoAddNew: '[elemento] Add new',
    elementoClearActive: '[elemento] Clear active',
    elementoUpdated: '[elemento] Updated',
    elementoDeleted: '[elemento] Deleted',
    elementoLoaded: '[elemento] Loaded',

    eventSetActive: '[event] Set active',
    eventLogout: '[event] Logout event',
    eventStartAddNew: '[event] Start Add New',
    eventAddNew: '[event] Add new',
    eventClearActiveEvent: '[event] Clear active event',
    eventUpdated: '[event] Event updated',
    eventDeleted: '[event] Event deleted',
    eventLoaded: '[event] Loaded',

    sistemaSetActive: '[sistema] Set active',
    sistemaLogout: '[sistema] Logout event',
    sistemaStartAddNew: '[sistema] Start Add New',
    sistemaAddNew: '[sistema] Add new',
    sistemaClearActive: '[sistema] Clear active',
    sistemaUpdated: '[sistema] Updated',
    sistemaDeleted: '[sistema] Deleted',
    sistemaLoaded: '[sistema] Loaded',

    proyectoSetActive: '[proyecto] Set active',
    proyectoLogout: '[proyecto] Logout event',
    proyectoStartAddNew: '[proyecto] Start Add New',
    proyectoAddNew: '[proyecto] Add new',
    proyectoClearActive: '[proyecto] Clear active',
    proyectoUpdated: '[proyecto] Updated',
    proyectoDeleted: '[proyecto] Deleted',
    proyectoLoaded: '[proyecto] Loaded',
    
    generoSetActive: '[genero] Set active',
    generoLogout: '[genero] Logout event',
    generoStartAddNew: '[genero] Start Add New',
    generoAddNew: '[genero] Add new',
    generoClearActive: '[genero] Clear active',
    generoUpdated: '[genero] Updated',
    generoDeleted: '[genero] Deleted',
    generoLoaded: '[genero] Loaded',
    
    subsistemaSetActive: '[subsistema] Set active',
    subsistemaLogout: '[subsistema] Logout event',
    subsistemaStartAddNew: '[subsistema] Start Add New',
    subsistemaAddNew: '[subsistema] Add new',
    subsistemaClearActive: '[subsistema] Clear active',
    subsistemaUpdated: '[subsistema] Updated',
    subsistemaDeleted: '[subsistema] Deleted',
    subsistemaLoaded: '[subsistema] Loaded',

    tareaSetActive: '[tarea] Set active',
    tareaLogout: '[tarea] Logout event',
    tareaStartAddNew: '[tarea] Start Add New',
    tareaAddNew: '[tarea] Add new',
    tareaClearActive: '[tarea] Clear active',
    tareaUpdated: '[tarea] Updated',
    tareaDeleted: '[tarea] Deleted',
    tareaLoaded: '[tarea] Loaded',

    tipoSetActive: '[tipo] Set active',
    tipoLogout: '[tipo] Logout event',
    tipoStartAddNew: '[tipo] Start Add New',
    tipoAddNew: '[tipo] Add new',
    tipoClearActive: '[tipo] Clear active',
    tipoUpdated: '[tipo] Updated',
    tipoDeleted: '[tipo] Deleted',
    tipoLoaded: '[tipo] Loaded',
}